### ISSUE TITLE
Load ML model into Tensorflow.js

### ISSUE THREAD

**Issue by TempixTL** [googleinterns/amaranth#31]

**Comment by TempixTL** [comment]
Been having a heck of a time getting this to work. So far I've ruled out using the `tensorflowjs` Python package to save the Keras model in JS format. I get this error when I attempt to: ``NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead.``, which doesn't make much sense.

By digging through  source code of the function that's used to do this conversion, `tensorflowjs.converters.save_keras_model()`, it turns out that a temp directory is created to store a `.h5` version of the model, which is then converted to JS format. Check it out [here](https://github.com/tensorflow/tfjs/blob/b5fc46b4110494882e491b529d01598b4209706c/tfjs-converter/python/tensorflowjs/converters/keras_h5_conversion.py#L313). Now that starts to make more sense, it seems some part of the model (most likely the experimental `TextVectorizer` layer) is unable to be serialized into the `.h5` format.

**Comment by TempixTL** [comment]
The other option to convert the Keras model is using the CLI tool `tensorflowjs_converter`. I get yet another vague error when attempting to use it: `AssertionError: Identity is not in graph`. Still looking into exactly what that means.

**Comment by TempixTL** [comment]
> The other option to convert the Keras model is using the CLI tool `tensorflowjs_converter`. I get yet another vague error when attempting to use it: `AssertionError: Identity is not in graph`. Still looking into exactly what that means.

Apparently this error is thrown while handling an earlier error:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.`

**Comment by TempixTL** [comment]
Tried with `tensorflowjs` versions `2.0.1post1`, `2.0.1`, and `2.0.0` and still no luck.

**Comment by TempixTL** [comment]
This error occurs with model files built on Tensorflow stable, and on tf-nightly. Not sure there's a way to go forward using TensorflowJS

**Comment by TempixTL** [comment]
Turns out my Python virtual environment may have been dirty. I believe my testing with different Tensorflow versions was muddied by the release of Tensorflow 2.3.0 yesterday! What timing.

After cleaning up my virtual environment and ensuring I have Tensorflow 2.2.0 (as well as the correct dependencies), I'm having much better luck. The ML model generated from this version is giving me a different error when attempting to convert to Tensorflow.js. First I got `ValueError: Unable to restore custom object of type _tf_keras_metric currently.`, which I've seen before. It's a result of using the F1Score metric from the `tensorflow_addons` module. After removing that from the serialized model, I'm working through a new error: `AssertionError: Some Python objects were not bound to checkpointed values, likely due to changes in the Python program`. I will be digging into this more today.

**Comment by TempixTL** [comment]
After finding a TextVectorization feature request issue on the official Tensorflow.js repo ([link](https://github.com/tensorflow/tfjs/issues/3303)) I might have to call this approach a dud. Definitive proof that there are currently no plans to support TextVectorization in Tensorflow.js.

**Comment by TempixTL** [comment]
Will switch to a server-based approach. Too bad!

**Comment by TempixTL** [comment]
Ok sike. Trying a few more things. One approach already tried was downloading the `text_vectorization.py` class to the project separately to use as a 'custom class.' This didn't work unfortunately. However, I'm going to experiment with serializing the text_vectorization separate from the model somehow.

**Comment by TempixTL** [comment]
Keras model does successfully convert to js format without `TextVectorization`! If it can be properly loaded into Tensorflow.js (likely) and the tokenization process can be serialized, we should be good to go.

**Comment by timmy-ch** [comment]
Yay!
